---
# This playbook configures 

- hosts: web
  remote_user: root
  tasks:
  - name: Install httpd and php
    yum: name={{ item }} state=present
    with_items:
     - httpd

  - name: Copies the config that allows unsafe options
    copy: src=config/unsafe.conf dest=/etc/httpd/conf.d/unsafe.conf
    notify: reload httpd

  handlers:
  - name: reload httpd
    systemd:
      name=httpd
      state=reloaded
      masked=no

